### ISSUE TITLE
Quantity in the individual bill reflect the total quantity that is input.

### ISSUE THREAD

**Issue by raprocks** [aditipolkam/bill-splitr#1]
![Screenshot_20220516-141617_Chrome.png](https://user-images.githubusercontent.com/52972480/168554643-81b6be48-1542-47f7-9d34-9f3f3d69e7ae.png)

The quantity in the individual bills must be total quantity divided by the number of people that have ordered it.

**Comment by aditipolkam** [comment]
![2022-05-21 (1)](https://user-images.githubusercontent.com/60136767/169655429-d00ec578-0776-46b7-a575-c786f7cbc222.png)
![2022-05-21](https://user-images.githubusercontent.com/60136767/169655431-fe5e3e4b-ec55-4cf0-a475-a9abbaa96ec2.png)

fixed the quantity and round figure issue :)

**Comment by aditipolkam** [comment]
![2022-05-21 (1)](https://user-images.githubusercontent.com/60136767/169655462-8784db8d-b8a3-4529-92a9-d03eddd0fe4c.png)
![2022-05-21](https://user-images.githubusercontent.com/60136767/169655470-a2a84ccc-cd7b-4ac5-849a-c564ef95e3a7.png)
fixed the quantity and round off price issue ser :)
